(lambda ( a )
  (if (>= (length a ) 24 )
    ( print (let* ((half-length (/ (length a ) 2))
           (sublist1 (subseq a 0 half-length))
           (sublist2 (subseq a half-length (length a)))
           (sum1 (reduce #'+ sublist1))
           (sum2 (reduce #'+ sublist2)))
      (= (+ sum1 sum2) 0)
    ))
  t)
)